name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  npm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script: [format:check, lint]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci
      - name: ${{ matrix.script }}
        run: npm run ${{ matrix.script }}
